### Basics of TensorFlow

In [1]:
import tensorflow as tf

# Create constants
a = tf.constant(2)
b = tf.constant(3)

# Perform basic operations
add = tf.add(a, b)
mul = tf.multiply(a, b)

print("Addition: ", add.numpy())
print("Multiplication: ", mul.numpy())


Addition:  5
Multiplication:  6


### Part 2: Working with Tensors


#### 2.1 Creating Tensors

In [2]:
# Creating a tensor from a list
tensor1 = tf.constant([1, 2, 3, 4])
print("Tensor1: ", tensor1)

# Creating a tensor with a specific shape
tensor2 = tf.constant([[1, 2], [3, 4]])
print("Tensor2: ", tensor2)


Tensor1:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Tensor2:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### 2.2 Tensor Operations

In [3]:
# Element-wise addition
tensor3 = tf.add(tensor1, tensor1)
print("Tensor3: ", tensor3)

# Matrix multiplication
tensor4 = tf.matmul(tensor2, tensor2)
print("Tensor4: ", tensor4)


Tensor3:  tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
Tensor4:  tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


### Part 3: Building Neural Networks

#### 3.1 Linear Regression
Let's implement a simple linear regression model using TensorFlow.

In [4]:
import numpy as np

# Generate some example data
x = np.random.rand(100).astype(np.float32)
y = 3.0 * x + 2.0 + np.random.normal(0, 0.1, 100)

# Create TensorFlow variables for the model parameters
W = tf.Variable(1.0)
b = tf.Variable(1.0)

# Define the linear regression model
def linear_regression(x):
    return W * x + b

# Define the loss function (mean squared error)
def loss(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Define the training step
optimizer = tf.optimizers.SGD(learning_rate=0.1)

def train_step(x, y):
    with tf.GradientTape() as tape:
        y_pred = linear_regression(x)
        loss_value = loss(y, y_pred)
    gradients = tape.gradient(loss_value, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return loss_value

# Training loop
for epoch in range(100):
    loss_value = train_step(x, y)
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss_value.numpy()}")

print(f"Trained W: {W.numpy()}, b: {b.numpy()}")


Epoch 0, Loss: 3.9965600967407227
Epoch 10, Loss: 0.1057320386171341
Epoch 20, Loss: 0.0742480680346489
Epoch 30, Loss: 0.06007574871182442
Epoch 40, Loss: 0.048914361745119095
Epoch 50, Loss: 0.04009473696351051
Epoch 60, Loss: 0.03312540426850319
Epoch 70, Loss: 0.027618229389190674
Epoch 80, Loss: 0.023266440257430077
Epoch 90, Loss: 0.01982765831053257
Trained W: 2.6294147968292236, b: 2.175489902496338


##### Note :
1. tf.GradientTape() is a context manager in TensorFlow used for automatic differentiation. 

2. tape.gradient(loss_value, [W, b])    :    TensorFlow is used to compute the gradients of a specified loss function with respect to a list of variables

3. This line updates the model parameters using the computed gradients. The optimizer should be defined elsewhere, typically as an instance of a TensorFlow optimizer (e.g., tf.optimizers.SGD, tf.optimizers.Adam, etc.). The apply_gradients method applies the gradients to the variables to minimize the loss. The zip function pairs each gradient with the corresponding variable.

#### Part 4: Deep Learning with TensorFlow
4.1 Building a Simple Neural Network

Let's build a simple feedforward neural network for classification using the Keras API, which is integrated into TensorFlow.

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Generate some example data
num_samples = 100000
num_features = 20
num_classes = 3

x = np.random.rand(num_samples, num_features)
y = np.random.randint(0, num_classes, num_samples)

# Define the neural network model
model = Sequential([
    Dense(64, activation='relu', input_shape=(num_features,)),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), 
              loss=SparseCategoricalCrossentropy(from_logits=False),
              metrics=['acc'])

# Train the model
model.fit(x, y, epochs=10, batch_size=64)

# Evaluate the model
loss, accuracy = model.evaluate(x, y)
print(f"Loss: {loss}, Accuracy: {accuracy}")


Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3102 - loss: 1.1155  
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - acc: 0.3862 - loss: 1.0961
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - acc: 0.3659 - loss: 1.0941
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3611 - loss: 1.0892 
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 71us/step - acc: 0.3838 - loss: 1.0862
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3910 - loss: 1.0871 
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - acc: 0.4208 - loss: 1.0786  
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.4368 - loss: 1.0721
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.4406 - loss: 1.0747 
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 242us/step - acc: 0.4538 - loss: 1.0632
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - acc: 0.4544 - loss: 1.0621
Loss: 1.0617644786834717, Accuracy: 0.45899999141693115


### Explanation

Epoch 1/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.2858 - loss: 1.1162  

Epoch 2/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - acc: 0.3486 - loss: 1.0982  

Epoch 3/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3519 - loss: 1.0936 

Epoch 4/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - acc: 0.3965 - loss: 1.0882

Epoch 5/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3843 - loss: 1.0845

Epoch 6/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.3876 - loss: 1.0821 

Epoch 7/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - acc: 0.4070 - loss: 1.0781  

Epoch 8/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.4126 - loss: 1.0775 

Epoch 9/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.4235 - loss: 1.0717 

Epoch 10/10

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - acc: 0.4589 - loss: 1.0667


#### Loss: 1.0575286149978638, Accuracy: 0.4659999907016754

#### For 1st epoch:

16/16: Indicates that the dataset is divided into 16 batches (mini-batches) for training in this epoch.

0s 1ms/step: The time taken per step (batch) is approximately 1 millisecond.

acc: 0.2858: The accuracy of the model after this epoch is 28.58%.

loss: 1.1162: The loss of the model after this epoch is 1.1162.

#### Note : here, 


#### Note :
##### loss=SparseCategoricalCrossentropy(from_logits=False)

##### Understanding Logits and Probabilities
##### Logits:
 These are raw scores or unnormalized values that a model outputs before applying an activation function like softmax. They can take any real values, and they are not constrained to be between 0 and 1 or to sum up to 1.

##### Probabilities: These are normalized values that represent the likelihood of each class, usually obtained by applying a softmax function to the logits. They are constrained to be between 0 and 1 and sum up to 1.

#### from_logits Parameter
##### from_logits=False:

Indicates that the predictions provided to the loss function are probabilities, not logits.
In this case, the model’s final layer should be a softmax layer (or another probability-producing layer) that converts logits to probabilities.
The loss function will directly use these probabilities to compute the loss.

### In TensorFlow and Keras, there are primarily two types of models you can build:














#### 1. Sequential Model:

The Sequential model is a linear stack of layers. It's simple and suitable for most feedforward neural networks where the layers are stacked in a sequence, one after the other.

Example

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])


c:\Users\s21\Desktop\my data\DeepLearning Frameworks\Tensorflow\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### 2. Functional API:

The Functional API is more flexible than the Sequential model. It allows you to build complex models such as multi-input, multi-output models, directed acyclic graphs, or models with shared layers.

Example

In [6]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

inputs = Input(shape=(784,))
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
outputs = Dense(10, activation='softmax')(x)
model = Model(inputs, outputs)


### Comparison
#### Sequential Model:

Pros: Simple to use, suitable for most feedforward networks.

Cons: Limited flexibility, cannot handle models with complex architectures (e.g., multi-input, multi-output, layer sharing).

#### Functional API:

Pros: Highly flexible, can handle complex architectures.

Cons: Slightly more complex to set up compared to the Sequential model.

### When to Use Each
#### Use Sequential Model when:

Your model consists of a single input tensor and a single output tensor.

The layers are stacked one after the other without any branching or merging.
#### Use Functional API when:

You need to build models with complex architectures.

Your model has multiple inputs or outputs.

Layers need to be reused or shared.